project/bookshelves/models.py
# None needed -- uses the Book model from booklists folder

project/booklists/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, HiddenField
from wtforms.validators import DataRequired, NumberRange, URL, AnyOf
from wtforms.widgets import TextArea


class BooklistForm(FlaskForm):
    title = HiddenField()#StringField('title', validators=[DataRequired()])
    author = HiddenField()#StringField('author', validators=[DataRequired()])
    categories=HiddenField()#StringField('categories') 
    snippet=HiddenField()#StringField('snippet') 
    description=HiddenField()#StringField('description')  
    pages=HiddenField()#StringField('pages')  
    image_url=HiddenField()#StringField('image_url')  
    preview_url=HiddenField()#StringField('preview_url')  
    date_published=HiddenField()#StringField('date_published') 
    nyt_review_url=HiddenField() 
    comments = StringField('comments', widget=TextArea())
    # rating = IntegerField('rating', validators=[NumberRange(min=1, max=10)])
    # review = StringField('review', widget=TextArea())

class EditBooklistForm(FlaskForm):
    comments = StringField('comments', widget=TextArea())

project/bookshelves/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, HiddenField, RadioField
from wtforms.validators import DataRequired, NumberRange, AnyOf, Email
from wtforms.widgets import TextArea


class BookshelfForm(FlaskForm):
    title = HiddenField()#StringField('title', validators=[DataRequired()])
    author = HiddenField()#StringField('author', validators=[DataRequired()])
    categories=HiddenField()#StringField('categories') 
    snippet=HiddenField()#StringField('snippet') 
    description=HiddenField()#StringField('description')  
    pages=HiddenField()#StringField('pages')  
    image_url=HiddenField()#StringField('image_url')  
    preview_url=HiddenField()#StringField('preview_url')  
    date_published=HiddenField()#StringField('date_published') 
    nyt_review_url=HiddenField() 
    rating = RadioField('rating', choices=[("1",1),("2",2),("3",3),("4",4),("5",5),("6",6),("7",7),("8",8),("9",9),("10",10)], default='1', validators=[DataRequired()])
    review = StringField('review', widget=TextArea())

class EditBookshelfForm(FlaskForm):
    rating = RadioField('rating', choices=[("1",1),("2",2),("3",3),("4",4),("5",5),("6",6),("7",7),("8",8),("9",9),("10",10)], default='1', validators=[DataRequired()])
    review = StringField('review', widget=TextArea())

class EmailForm(FlaskForm):
    recipient = StringField('email', validators=[DataRequired(), Email()])

project/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email, Length

class UserForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    password = PasswordField('password', validators=[Length(min=6)])
    name = StringField('name', validators=[DataRequired()])
    email = StringField('email', validators=[DataRequired(), Email()])

class UpdateForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    name = StringField('name', validators=[DataRequired()])
    email = StringField('email', validators=[DataRequired(), Email()])

class UpdatePasswordForm(FlaskForm):
    old_password = PasswordField('old_password', validators=[Length(min=6)])
    new_password = PasswordField('new_password', validators=[Length(min=6)])
    confirm_password = PasswordField('confirm_password', validators=[Length(min=6)])

class LogInForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    password = PasswordField('password', validators=[Length(min=6)])

project/__init__.py
from flask import Flask, url_for, redirect, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_modus import Modus
from flask_bcrypt import Bcrypt
from flask_login import LoginManager, current_user
from flask_mail import Mail
import os

app = Flask(__name__)

if os.environ.get('ENV') == 'production':
    app.config.from_object('config.ProductionConfig')
else:
    app.config.from_object('config.DevelopmentConfig')

app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SQLALCHEMY_ECHO'] = False
app.config['TEMPLATES_AUTO_RELOAD'] = True
app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY') or "who knows"
app.config.update(dict(
    DEBUG = False,
    MAIL_SERVER = 'smtp.googlemail.com',
    MAIL_PORT = 587,
    MAIL_USE_TLS = True,
    MAIL_USE_SSL = False,
    MAIL_USERNAME = 'mybookshelvesapp@gmail.com',
    MAIL_PASSWORD = 'webinarz',
    ADMINS = ['katielkrieger@gmail.com']
))
app.jinja_env.auto_reload = False

modus = Modus(app)
bcrypt = Bcrypt(app)
login_manager = LoginManager(app)
db = SQLAlchemy(app)
mail = Mail(app)

from project.users.views import users_blueprint
from project.booklists.views import booklists_blueprint
from project.bookshelves.views import bookshelves_blueprint

app.register_blueprint(users_blueprint, url_prefix='/users')
app.register_blueprint(booklists_blueprint, url_prefix='/users/<int:user_id>/booklists')
app.register_blueprint(bookshelves_blueprint, url_prefix='/users/<int:user_id>/bookshelves')

from project.users.models import User, Booklist

login_manager.init_app(app)
login_manager.login_view = "users.login"

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

@app.route('/')
def root():
    if current_user.is_anonymous:
        return render_template('home.html')
    else:
        following = current_user.all_following
        following_ids = [f.id for f in following]
        bookshelves = Booklist.query.filter(Booklist.user_id.in_(following_ids)).order_by("rating desc").limit(120).all()
        return redirect(url_for('users.index', books=bookshelves))

project/booklists/views.py
from flask import redirect, render_template, request, url_for, Blueprint, flash
from project.booklists.models import Book
from project.users.models import User, Booklist
from project.booklists.forms import BooklistForm, EditBooklistForm
from project.bookshelves.forms import EditBookshelfForm
from project import db, bcrypt
from sqlalchemy.exc import IntegrityError
from flask_login import current_user, login_required
from functools import wraps

booklists_blueprint = Blueprint(
  'booklists',
  __name__,
  template_folder='templates'
)

def ensure_correct_user(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        if kwargs.get('user_id') != current_user.id:
            flash("Not authorized")
            return redirect(url_for('users.index'))
        return fn(*args, **kwargs)
    return wrapper

@booklists_blueprint.route('/', methods=["GET","POST"])
@login_required
def index(user_id):
  user = User.query.get_or_404(user_id)
  form = BooklistForm(request.form)
  if request.method == "POST":
    if form.validate():
      new_book = Book(
        title=request.form['title'],
        author=request.form['author'],
        categories=request.form['categories'],
        snippet=request.form['snippet'],
        description=request.form['description'],
        pages=request.form['pages'],
        image_url=request.form['image_url'],
        preview_url=request.form['preview_url'],
        date_published=request.form['date_published'],
        nyt_review_url=request.form['nyt_review_url'] 
      )
      # check if this book is already in the database - if it is, don't add it
      found_book = Book.query.filter_by(title=new_book.title).filter_by(author=new_book.author)
      if found_book.count() > 0:
        book_to_add=found_book.first()
      else:
        # only if not in the database already
        db.session.add(new_book)
        db.session.commit()
        book_to_add=new_book
      new_booklist = Booklist(
        list_type='booklist',
        comments=request.form['comments'],
        rating=1,
        review='',
        user=user,
        book=book_to_add
      )
      db.session.add(new_booklist)
      db.session.commit()
      flash("Book added successfully!")
      return redirect(url_for('booklists.index', user_id=user_id))
    flash("Please try again")
    return render_template('booklists/new.html', form=form, user=user)
  all_books = Booklist.query.filter_by(user=user).filter_by(list_type="booklist").all()
  # Look into N+1 query issue
  return render_template('booklists/index.html', form=form, user=user, books=all_books)


@booklists_blueprint.route('/new')
@login_required
@ensure_correct_user
def new(user_id):
  form = BooklistForm(request.form)
  user = User.query.get_or_404(user_id)
  return render_template('booklists/new.html', form=form, user=user)

@booklists_blueprint.route('/<int:book_id>', methods=["POST","PATCH","DELETE"])
@login_required
@ensure_correct_user
def show(user_id, book_id):
  book = Book.query.get_or_404(book_id)
  user = User.query.get_or_404(user_id)
  if request.method== "POST":
    form = EditBooklistForm(request.form)
    if form.validate():
      new_booklist = Booklist(
        list_type='booklist',
        comments=request.form['comments'],
        rating=1,
        review='',
        user=user,
        book=book
      )
      db.session.add(new_booklist)
      db.session.commit()
      flash("Book added successfully!")
      return redirect(url_for('booklists.index', user_id=user_id))
    flash("Please try again")
    return render_template('booklists/new.html', form=form, user=user)

  booklist = Booklist.query.filter_by(user=user).filter_by(book=book).first()
  if request.method == b"PATCH":
    form = EditBooklistForm(request.form)
    if form.validate():
      # make it so they can only update the comments OR move to their bookshelf!!!!!
      booklist.comments = request.form['comments']
      db.session.add(booklist)
      db.session.commit()
      flash("Book successfully updated")
      return redirect(url_for('booklists.index', user_id=user_id))
  if request.method == b"DELETE":
    form = EditBooklistForm(request.form)
    if form.validate():
      db.session.delete(booklist)
      # db.session.delete(book)
      db.session.commit()
      flash("Book successfully removed from your booklist")
      return redirect(url_for('booklists.index', user_id=user_id))

@booklists_blueprint.route('/<int:book_id>', methods=["GET"])
@login_required
# @ensure_correct_user
def show_get(user_id, book_id):
  book = Book.query.get_or_404(book_id)
  user = User.query.get_or_404(user_id)
  booklist = Booklist.query.filter_by(user=user).filter_by(book=book).first()
  full_bookshelf = Booklist.query.filter_by(book=book).filter_by(list_type="bookshelf").all()
  if len([b.rating for b in full_bookshelf]) == 0:
    average_rating = "No ratings yet"
  else:
    average_rating = round(sum([b.rating for b in full_bookshelf])/len([b.rating for b in full_bookshelf])/1)
  if booklist.user.id !=  current_user.id:
    form = EditBooklistForm(request.form)
  else:
    form = EditBookshelfForm(request.form)
  return render_template('booklists/show.html', book=booklist, form=form, user=user, full_bookshelf=full_bookshelf, average_rating=average_rating)

@booklists_blueprint.route('/<int:book_id>/edit')
@login_required
@ensure_correct_user
def edit(user_id, book_id):
  # Need to think about how to let them move a book to their bookshelf!!!!!!
  book = Book.query.get_or_404(book_id)
  user = User.query.get_or_404(user_id)
  form = EditBooklistForm(request.form)
  return render_template('booklists/edit.html', book=book, form=form, user=user)

project/bookshelves/views.py
from flask import redirect, render_template, request, url_for, Blueprint, flash
from flask_mail import Message
from project.booklists.models import Book
from project.users.models import User, Booklist
from project.bookshelves.forms import BookshelfForm, EditBookshelfForm, EmailForm
from project.booklists.forms import EditBooklistForm
from project import db, bcrypt, mail
from sqlalchemy.exc import IntegrityError
from sqlalchemy.sql import func
from flask_login import current_user, login_required
from functools import wraps

bookshelves_blueprint = Blueprint(
  'bookshelves',
  __name__,
  template_folder='templates'
)

def ensure_correct_user(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        if kwargs.get('user_id') != current_user.id:
            flash("Not authorized")
            return redirect(url_for('users.index'))
        return fn(*args, **kwargs)
    return wrapper

@bookshelves_blueprint.route('/', methods=["GET","POST"])
@login_required
def index(user_id):
  user = User.query.get_or_404(user_id)
  form = BookshelfForm(request.form)
  if request.method == "POST":
    if form.validate():
      new_book = Book(
        title=request.form['title'],
        author=request.form['author'],
        categories=request.form['categories'],
        snippet=request.form['snippet'],
        description=request.form['description'],
        pages=request.form['pages'],
        image_url=request.form['image_url'],
        preview_url=request.form['preview_url'],
        date_published=request.form['date_published'],
        nyt_review_url=request.form['nyt_review_url']
      )
      # check if this book is already in the database - if it is, don't add it
      found_book = Book.query.filter_by(title=new_book.title).filter_by(author=new_book.author)
      if found_book.count() > 0:
        book_to_add=found_book.first()
      else:
        # only if not in the database already
        db.session.add(new_book)
        db.session.commit()
        book_to_add=new_book
      new_bookshelf = Booklist(
        list_type='bookshelf',
        comments='',
        rating=request.form['rating'],
        review=request.form['review'],
        user=user,
        book=book_to_add
      )
      db.session.add(new_bookshelf)
      db.session.commit()
      flash("Book added successfully!")
      return redirect(url_for('bookshelves.index', user_id=user_id))
    flash("Please try again")
    return render_template('bookshelves/new.html', form=form, user=user)
  all_books = Booklist.query.filter_by(user=user).filter_by(list_type="bookshelf").all()
  # Look into N+1 query issue
  return render_template('bookshelves/index.html', form=form, user=user, books=all_books)


@bookshelves_blueprint.route('/new')
@login_required
@ensure_correct_user
def new(user_id):
  form = BookshelfForm(request.form)
  user = User.query.get_or_404(user_id)
  return render_template('bookshelves/new.html', form=form, user=user)

@bookshelves_blueprint.route('/<int:book_id>', methods=["PATCH","DELETE"])
@login_required
@ensure_correct_user
def show(user_id, book_id):
  book = Book.query.get_or_404(book_id)
  user = User.query.get_or_404(user_id)
  bookshelf = Booklist.query.filter_by(user=user).filter_by(book=book).first()
  form = EditBookshelfForm(request.form)
  if request.method == b"PATCH":
    if form.validate():
      bookshelf.rating = request.form['rating']
      bookshelf.review = request.form['review']
      bookshelf.list_type = "bookshelf"
      db.session.add(bookshelf)
      db.session.commit()
      flash("Book successfully updated")
      return redirect(url_for('bookshelves.index', user_id=user_id))
  if request.method == b"DELETE":
    if form.validate():
      db.session.delete(bookshelf)
      # db.session.delete(book)
      db.session.commit()
      flash("Book successfully removed from your bookshelf")
      return redirect(url_for('bookshelves.index', user_id=user_id))

@bookshelves_blueprint.route('/<int:book_id>', methods=["GET"])
@login_required
# @ensure_correct_user
def show_get(user_id, book_id):
  book = Book.query.get_or_404(book_id)
  user = User.query.get_or_404(user_id)
  bookshelf = Booklist.query.filter_by(user=user).filter_by(book=book).first()
  full_bookshelf = Booklist.query.filter_by(book=book).filter_by(list_type="bookshelf").all()
  if len([b.rating for b in full_bookshelf]) == 0:
    average_rating = "No ratings yet"
  else:
    average_rating = round(sum([b.rating for b in full_bookshelf])/len([b.rating for b in full_bookshelf]),1)
  if bookshelf.user.id !=  current_user.id:
    form = EditBooklistForm(request.form)
  else:
    form = EmailForm(request.form)
  return render_template('bookshelves/show.html', book=bookshelf, form=form, user=user, full_bookshelf=full_bookshelf, average_rating=average_rating)

@bookshelves_blueprint.route('/<int:book_id>/edit')
@login_required
@ensure_correct_user
def edit(user_id, book_id):
  # Need to think about how to let them move a book to their bookshelf!!!!!!
  book = Book.query.get_or_404(book_id)
  user = User.query.get_or_404(user_id)
  form = EditBookshelfForm(request.form)
  return render_template('bookshelves/edit.html', book=book, form=form, user=user)

@bookshelves_blueprint.route('/<int:book_id>/email',methods=["POST"])
@login_required
@ensure_correct_user
def email(user_id, book_id):
  form = EmailForm(request.form)
  book = Book.query.get_or_404(book_id)
  user = User.query.get_or_404(user_id)
  bookshelf = Booklist.query.filter_by(user=user).filter_by(book=book).first()
  recipients = request.form['recipient'].split(',')

  if form.validate_on_submit():
    msg = Message("Here's a book I thought you might like",
                sender=(current_user.name,current_user.email),
                recipients=recipients)
    msg.body = render_template('bookshelves/email.html', user=user, book=bookshelf)
    msg.html = render_template('bookshelves/email.html', user=user, book=bookshelf)
    mail.send(msg)
    return redirect(url_for('bookshelves.index', user_id=user.id))
  flash("Invalid email address. Please try again.")
  return render_template('bookshelves/show.html', form=form, book=bookshelf, user=user)

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Bookshelf</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"></script>
    <!-- Latest compiled and minified CSS -->
    {# <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"> #}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/paper/bootstrap.min.css">
    
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    <script src="{{ url_for('static', filename='scripts/script.js') }}"></script>

    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">

    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/style.css') }}">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='slick/slick.css') }}"/>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='slick/slick-theme.css') }}"/>

    <script type="text/javascript" src="{{ url_for('static', filename='slick/slick.min.js') }}"></script>
</head>
<body id="bootstrap-overrides">
  <nav class="navbar navbar-default navbar-color">
    <div class="container-fluid">
      <div class="navbar-header">
        <a href="{{ url_for('root') }}" class="navbar-brand">
          {# <img src="{{ url_for('static', filename='images/warbler-logo.png') }}" alt=""> #}
          <span class="white">My Bookshelves</span>
        </a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_anonymous %}
          <li><a href="{{ url_for('users.signup') }}">Sign up</a></li>
          <li><a href="{{ url_for('users.login') }}">Log in</a></li>
        {% else %}
          <li><a href="{{ url_for('users.show', user_id=current_user.id) }}">
            {{ current_user.username }}
          </a></li>
          <li><a href="{{ url_for('booklists.new', user_id=current_user.id) }}">Add to Booklist</a></li>
          <li><a href="{{ url_for('bookshelves.new', user_id=current_user.id) }}">Add to Bookshelf</a></li>
          <li><a href="{{ url_for('users.logout') }}">Log out</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
  {# <img src="{{ url_for('static', filename='images/home-cropped-top.jpg') }}" class="top-img">
 #}

  <div class="container-fluid main">
    <section>
      {% block content %}
      {% endblock %}     
    </section>

    <footer>
      <div class="row bottom text-center">
        <img src="{{ url_for('static', filename='images/home-cropped.jpg') }}" class="bottom-img">
      </div>
    </footer>
  </div>
    
</body>
</html>

project/templates/d3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Bookshelf</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"></script>
    <!-- Latest compiled and minified CSS -->
    {# <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"> #}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/paper/bootstrap.min.css">
    
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    <script src="{{ url_for('static', filename='scripts/script.js') }}"></script>

    <script src="{{ url_for('static', filename='scripts/d3.js') }}"></script>

    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">

    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/style.css') }}">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='slick/slick.css') }}"/>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='slick/slick-theme.css') }}"/>

    <script src="https://d3js.org/d3.v4.js"></script>

    <script type="text/javascript" src="{{ url_for('static', filename='slick/slick.min.js') }}"></script>
</head>
<body id="bootstrap-overrides">
  <nav class="navbar navbar-default navbar-color">
    <div class="container-fluid">
      <div class="navbar-header">
        <a href="{{ url_for('root') }}" class="navbar-brand">
          {# <img src="{{ url_for('static', filename='images/warbler-logo.png') }}" alt=""> #}
          <span class="white">My Bookshelves</span>
        </a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_anonymous %}
          <li><a href="{{ url_for('users.signup') }}">Sign up</a></li>
          <li><a href="{{ url_for('users.login') }}">Log in</a></li>
        {% else %}
          <li><a href="{{ url_for('users.show', user_id=current_user.id) }}">
            {{ current_user.username }}
          </a></li>
          <li><a href="{{ url_for('booklists.new', user_id=current_user.id) }}">Add to Booklist</a></li>
          <li><a href="{{ url_for('bookshelves.new', user_id=current_user.id) }}">Add to Bookshelf</a></li>
          <li><a href="{{ url_for('users.logout') }}">Log out</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <!-- <img src="{{ url_for('static', filename='images/home-cropped-top.jpg') }}" class="top-img"> -->

  <div class="container-fluid main">
    <section>
      {% block content %}
      {% endblock %}     
    </section>

    <footer>
      <div class="row bottom text-center">
        <img src="{{ url_for('static', filename='images/home-cropped.jpg') }}" class="bottom-img">
      </div>
    </footer>
  </div>
    
</body>
</html>

project/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Bookshelf</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"></script>
    <!-- Latest compiled and minified CSS -->
    {# <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"> #}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/paper/bootstrap.min.css">
    
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    <script src="{{ url_for('static', filename='scripts/script.js') }}"></script>

    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">

    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/style-home.css') }}">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='slick/slick.css') }}"/>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='slick/slick-theme.css') }}"/>

    <script type="text/javascript" src="{{ url_for('static', filename='slick/slick.min.js') }}"></script>

</head>
<body class="background">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a href="{{ url_for('root') }}" class="navbar-brand">
          {# <img src="{{ url_for('static', filename='images/warbler-logo.png') }}" alt=""> #}
          <span>My Bookshelves</span>
        </a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_anonymous %}
          <li><a href="{{ url_for('users.signup') }}">Sign up</a></li>
          <li><a href="{{ url_for('users.login') }}">Log in</a></li>
        {% else %}
          <li><a href="{{ url_for('users.show', user_id=current_user.id) }}">
            {{ current_user.username }}
          </a></li>
          <li><a href="{{ url_for('booklists.new', user_id=current_user.id) }}">Add to Booklist</a></li>
          <li><a href="{{ url_for('bookshelves.new', user_id=current_user.id) }}">Add to Bookshelf</a></li>
          <li><a href="{{ url_for('users.logout') }}">Log out</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

  {% for message in get_flashed_messages() %}
    <div class="alert alert-info">{{ message }}</div>
  {% endfor %}

 {#  <section class="container">
    <h1 class="yellow">
      <div>Never find yourself</div>
      <div>without a good book again</div>
    </h1>     
  </section> #}

  <div class="carousel container">
    <div>
      <h1 class="yellow">
        <div>Never find yourself</div>
        <div>without a good book again</div>
      </h1>  
    </div>
    <div>
      <h1 class="yellow">
        <div>See what others</div>
        <div>are reading</div>
      </h1>
    </div>
    <div>
      <h1 class="yellow">
        <div>Keep track of books</div>
        <div>you want to read</div>
      </h1>
    </div>
    <div>
      <h1 class="yellow">
        <div>Write your own reviews</div>
        <div>to share with others</div>
      </h1>
    </div>
    <div>
      <h1 class="yellow">
        <div>Sign up today</div>
        <div>to try it for yourself</div>
      </h1>
    </div>
  </div>
    
</body>
</html>