project/users/models.py
from project import db, bcrypt
from flask_login import UserMixin
from project.booklists.models import Book


FollowersFollowee = db.Table('follows',
                              db.Column('id',
                                        db.Integer,
                                        primary_key=True),
                              db.Column('followee_id',
                                        db.Integer,
                                        db.ForeignKey('users.id', ondelete="cascade")),
                              db.Column('follower_id',
                                        db.Integer,
                                        db.ForeignKey('users.id', ondelete="cascade")),
                              db.CheckConstraint('follower_id != followee_id', name="no_self_follow"))


class User(db.Model, UserMixin):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.Text, unique=True)
    password = db.Column(db.Text)
    name = db.Column(db.Text)
    email = db.Column(db.Text)
    followers = db.relationship("User",
                              secondary=FollowersFollowee,
                              primaryjoin=(FollowersFollowee.c.followee_id == id),
                              secondaryjoin=(FollowersFollowee.c.follower_id == id),
                              backref=db.backref('following', lazy='dynamic'),
                              lazy='dynamic')
    all_followers = db.relationship("User",
                              secondary=FollowersFollowee,
                              primaryjoin=(FollowersFollowee.c.followee_id == id),
                              secondaryjoin=(FollowersFollowee.c.follower_id == id),
                              backref=db.backref('all_following', lazy='joined'),
                              lazy='joined')

    def __init__(self, username, password, name, email):
        self.username = username
        self.password = bcrypt.generate_password_hash(password).decode('UTF-8')
        self.name = name
        self.email = email

    def __repr__(self):
        return "User #{}: username: {} (email: {})".format(self.id, self.username, self.email)

    def is_followed_by(self, user):
        return bool(self.followers.filter_by(id=user.id).first())

    def is_following(self, user):
        return bool(self.following.filter_by(id=user.id).first())

class Booklist(db.Model, UserMixin):

    __tablename__ = 'booklists'

    id = db.Column(db.Integer,primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id', ondelete="cascade"))
    book_id = db.Column(db.Integer, db.ForeignKey('books.id', ondelete="cascade"))
    list_type = db.Column(db.Text)
    comments = db.Column(db.Text)
    rating = db.Column(db.Integer)
    review = db.Column(db.Text)

    user = db.relationship(User, backref="booklists")
    book = db.relationship(Book, backref="booklists")

    def __init__(self, list_type, comments, rating, review, user, book):
        self.list_type = list_type
        self.comments = comments
        self.rating = rating
        self.review = review
        self.user = user
        self.book = book

    def __repr__(self):
        return "Book {} on {}'s list".format(self.book.title, self.user.username)

project/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email, Length

class UserForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    password = PasswordField('password', validators=[Length(min=6)])
    name = StringField('name', validators=[DataRequired()])
    email = StringField('email', validators=[DataRequired(), Email()])

class UpdateForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    name = StringField('name', validators=[DataRequired()])
    email = StringField('email', validators=[DataRequired(), Email()])

class UpdatePasswordForm(FlaskForm):
    old_password = PasswordField('old_password', validators=[Length(min=6)])
    new_password = PasswordField('new_password', validators=[Length(min=6)])
    confirm_password = PasswordField('confirm_password', validators=[Length(min=6)])

class LogInForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    password = PasswordField('password', validators=[Length(min=6)])

project/bookshelves/views.py
from flask import redirect, render_template, request, url_for, Blueprint, flash
from flask_mail import Message
from project.booklists.models import Book
from project.users.models import User, Booklist
from project.bookshelves.forms import BookshelfForm, EditBookshelfForm, EmailForm
from project.booklists.forms import EditBooklistForm
from project import db, bcrypt, mail
from sqlalchemy.exc import IntegrityError
from sqlalchemy.sql import func
from flask_login import current_user, login_required
from functools import wraps

bookshelves_blueprint = Blueprint(
  'bookshelves',
  __name__,
  template_folder='templates'
)

def ensure_correct_user(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        if kwargs.get('user_id') != current_user.id:
            flash("Not authorized")
            return redirect(url_for('users.index'))
        return fn(*args, **kwargs)
    return wrapper

@bookshelves_blueprint.route('/', methods=["GET","POST"])
@login_required
def index(user_id):
  user = User.query.get_or_404(user_id)
  form = BookshelfForm(request.form)
  if request.method == "POST":
    if form.validate():
      new_book = Book(
        title=request.form['title'],
        author=request.form['author'],
        categories=request.form['categories'],
        snippet=request.form['snippet'],
        description=request.form['description'],
        pages=request.form['pages'],
        image_url=request.form['image_url'],
        preview_url=request.form['preview_url'],
        date_published=request.form['date_published'],
        nyt_review_url=request.form['nyt_review_url']
      )
      # check if this book is already in the database - if it is, don't add it
      found_book = Book.query.filter_by(title=new_book.title).filter_by(author=new_book.author)
      if found_book.count() > 0:
        book_to_add=found_book.first()
      else:
        # only if not in the database already
        db.session.add(new_book)
        db.session.commit()
        book_to_add=new_book
      new_bookshelf = Booklist(
        list_type='bookshelf',
        comments='',
        rating=request.form['rating'],
        review=request.form['review'],
        user=user,
        book=book_to_add
      )
      db.session.add(new_bookshelf)
      db.session.commit()
      flash("Book added successfully!")
      return redirect(url_for('bookshelves.index', user_id=user_id))
    flash("Please try again")
    return render_template('bookshelves/new.html', form=form, user=user)
  all_books = Booklist.query.filter_by(user=user).filter_by(list_type="bookshelf").all()
  # Look into N+1 query issue
  return render_template('bookshelves/index.html', form=form, user=user, books=all_books)


@bookshelves_blueprint.route('/new')
@login_required
@ensure_correct_user
def new(user_id):
  form = BookshelfForm(request.form)
  user = User.query.get_or_404(user_id)
  return render_template('bookshelves/new.html', form=form, user=user)

@bookshelves_blueprint.route('/<int:book_id>', methods=["PATCH","DELETE"])
@login_required
@ensure_correct_user
def show(user_id, book_id):
  book = Book.query.get_or_404(book_id)
  user = User.query.get_or_404(user_id)
  bookshelf = Booklist.query.filter_by(user=user).filter_by(book=book).first()
  form = EditBookshelfForm(request.form)
  if request.method == b"PATCH":
    if form.validate():
      bookshelf.rating = request.form['rating']
      bookshelf.review = request.form['review']
      bookshelf.list_type = "bookshelf"
      db.session.add(bookshelf)
      db.session.commit()
      flash("Book successfully updated")
      return redirect(url_for('bookshelves.index', user_id=user_id))
  if request.method == b"DELETE":
    if form.validate():
      db.session.delete(bookshelf)
      # db.session.delete(book)
      db.session.commit()
      flash("Book successfully removed from your bookshelf")
      return redirect(url_for('bookshelves.index', user_id=user_id))

@bookshelves_blueprint.route('/<int:book_id>', methods=["GET"])
@login_required
# @ensure_correct_user
def show_get(user_id, book_id):
  book = Book.query.get_or_404(book_id)
  user = User.query.get_or_404(user_id)
  bookshelf = Booklist.query.filter_by(user=user).filter_by(book=book).first()
  full_bookshelf = Booklist.query.filter_by(book=book).filter_by(list_type="bookshelf").all()
  if len([b.rating for b in full_bookshelf]) == 0:
    average_rating = "No ratings yet"
  else:
    average_rating = round(sum([b.rating for b in full_bookshelf])/len([b.rating for b in full_bookshelf]),1)
  if bookshelf.user.id !=  current_user.id:
    form = EditBooklistForm(request.form)
  else:
    form = EmailForm(request.form)
  return render_template('bookshelves/show.html', book=bookshelf, form=form, user=user, full_bookshelf=full_bookshelf, average_rating=average_rating)

@bookshelves_blueprint.route('/<int:book_id>/edit')
@login_required
@ensure_correct_user
def edit(user_id, book_id):
  # Need to think about how to let them move a book to their bookshelf!!!!!!
  book = Book.query.get_or_404(book_id)
  user = User.query.get_or_404(user_id)
  form = EditBookshelfForm(request.form)
  return render_template('bookshelves/edit.html', book=book, form=form, user=user)

@bookshelves_blueprint.route('/<int:book_id>/email',methods=["POST"])
@login_required
@ensure_correct_user
def email(user_id, book_id):
  form = EmailForm(request.form)
  book = Book.query.get_or_404(book_id)
  user = User.query.get_or_404(user_id)
  bookshelf = Booklist.query.filter_by(user=user).filter_by(book=book).first()
  recipients = request.form['recipient'].split(',')

  if form.validate_on_submit():
    msg = Message("Here's a book I thought you might like",
                sender=(current_user.name,current_user.email),
                recipients=recipients)
    msg.body = render_template('bookshelves/email.html', user=user, book=bookshelf)
    msg.html = render_template('bookshelves/email.html', user=user, book=bookshelf)
    mail.send(msg)
    return redirect(url_for('bookshelves.index', user_id=user.id))
  flash("Invalid email address. Please try again.")
  return render_template('bookshelves/show.html', form=form, book=bookshelf, user=user)

project/users/views.py
from flask import redirect, render_template, request, url_for, Blueprint, flash
from project.users.models import User, Booklist
from project.users.forms import UserForm, UpdateForm, LogInForm, UpdatePasswordForm
from project import db, bcrypt
from sqlalchemy.exc import IntegrityError
from flask_login import login_user, logout_user, current_user, login_required
from functools import wraps
import json

users_blueprint = Blueprint(
  'users',
  __name__,
  template_folder='templates'
)

def ensure_correct_user(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        if kwargs.get('user_id') != current_user.id:
            flash("Not authorized")
            return redirect(url_for('users.index'))
        return fn(*args, **kwargs)
    return wrapper

@users_blueprint.route('/')
@login_required
def index():
    following = current_user.all_following
    following_ids = [f.id for f in following]
    bookshelves = Booklist.query.filter_by(list_type="bookshelf").filter(Booklist.user_id.in_(following_ids)).order_by("rating desc").limit(120).all()
    return render_template('users/index.html', books=bookshelves)

@users_blueprint.route('/discover')
@login_required
def discover():
    bookshelves = Booklist.query.filter_by(list_type="bookshelf").order_by("rating desc").limit(120).all()
    return render_template('users/discover.html', books=bookshelves)

@users_blueprint.route('/signup', methods=["GET", "POST"])
def signup():
    form = UserForm(request.form)
    if request.method == "POST":
        if form.validate():
            try:
                new_user = User(
                    request.form['username'], 
                    request.form['password'], 
                    request.form['name'], 
                    request.form['email']
                )
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user)
                flash("Welcome {}!".format(new_user.username))
                return redirect(url_for('users.index'))
            except IntegrityError as e:
                flash("Username has been taken")
                return render_template('users/signup.html', form=form)
    return render_template('users/signup.html', form=form)

@users_blueprint.route('/login', methods=["GET","POST"])
def login():
    form = LogInForm(request.form)
    if request.method == "POST":
        if form.validate():
            found_user = User.query.filter_by(username = form.username.data).first()
            if found_user:
                authenticated_user = bcrypt.check_password_hash(found_user.password, request.form['password'])
                if authenticated_user:
                    login_user(found_user)
                    flash("Welcome {}!".format(found_user.username))
                    return redirect(url_for('users.show', user_id=current_user.id))
            flash("Username and password do not match")
            return render_template('users/login.html', form=form)
    return render_template('users/login.html', form=form)

@users_blueprint.route('/logout')
@login_required
def logout():
    flash ("You are now logged out")
    logout_user()
    return redirect(url_for('root'))

@users_blueprint.route('/<int:user_id>', methods=["GET","PATCH","DELETE"])
@login_required
def show(user_id):
    found_user = User.query.get_or_404(user_id)
    if request.method == b"PATCH":
        form = UpdateForm(request.form)
        if form.validate():
            found_user.username = request.form['username']
            found_user.name = request.form['name']
            found_user.email = request.form['email']
            db.session.add(found_user)
            db.session.commit()
            return redirect(url_for('users.index'))
        return render_template("users/edit.html", form=form, user=found_user)
    if request.method == b"DELETE":
        db.session.delete(found_user)
        db.session.commit()
        return redirect(url_for('users.index'))
    booklist = Booklist.query.filter_by(user=found_user).filter_by(list_type="booklist").all()
    bookshelf = Booklist.query.filter_by(user=found_user).filter_by(list_type="bookshelf").all()
    rating_list = [book.rating for book in bookshelf]
    if len(rating_list) == 0:
        average_rating = "None"
    else:
        average_rating = round(sum(rating_list) / len(rating_list),1)
    return render_template('users/show.html', user=found_user, booklist=booklist, bookshelf=bookshelf, average_rating=average_rating)

@users_blueprint.route('/<int:user_id>/edit')
@login_required
@ensure_correct_user
def edit(user_id):
    user = User.query.get_or_404(user_id)
    form = UserForm(request.form)
    return render_template('users/edit.html', form=form, user=user)

@users_blueprint.route('/<int:user_id>/edit_password', methods=["GET", "PATCH"])
@login_required
@ensure_correct_user
def edit_password(user_id):
    found_user = User.query.get_or_404(user_id)
    if request.method == b"PATCH":
        form = UpdatePasswordForm(request.form)
        if form.validate():
            authenticated_user = bcrypt.check_password_hash(found_user.password, request.form['old_password'])
            if authenticated_user and (request.form['new_password'] == request.form['confirm_password']):
                found_user.password = bcrypt.generate_password_hash(request.form['new_password']).decode('UTF-8')
                db.session.add(found_user)
                db.session.commit()
                flash("Password updated successfully")
                return redirect(url_for('users.index'))
            flash("Passwords do not match. Please try again.")
            return render_template("users/edit_password.html", form=form, user=found_user)
        flash("Please correct errors shown and resubmit")
        return render_template("users/edit_password.html", form=form, user=found_user)
    form = UpdatePasswordForm()
    return render_template('users/edit_password.html', form=form, user=found_user)

@users_blueprint.route('/<int:follower_id>/follower', methods=['POST', 'DELETE'])
@login_required
def follower(follower_id):
  followed = User.query.get(follower_id)
  if request.method == 'POST':
    current_user.following.append(followed)
  else:
    current_user.following.remove(followed)
  db.session.add(current_user)
  db.session.commit()
  return redirect(url_for('users.following', user_id=current_user.id))

@users_blueprint.route('/<int:user_id>/following', methods=['GET'])
@login_required
def following(user_id):
  return render_template('users/following.html', user=User.query.get(user_id))

@users_blueprint.route('/<int:user_id>/followers', methods=['GET'])
@login_required
def followers(user_id):
  return render_template('users/followers.html', user=User.query.get(user_id))

@users_blueprint.route('/<int:user_id>/d3.json')
def d3(user_id):
  found_user = User.query.get_or_404(user_id)
  books = Booklist.query.filter_by(user=found_user).filter_by(list_type="bookshelf").all()
  d3_list = [{"rating": b.rating, "pages": int(b.book.pages), "title": b.book.title, "bookshelf_id": b.book.id} for b in books]
  return json.dumps(d3_list)

project/users/templates/users/discover.html
{% extends 'base.html' %}
{% block content %}

{% for message in get_flashed_messages() %}
  <div class="alert alert-info">{{ message }}</div>
{% endfor %}


<h2 class="text-center">Think big
</h2>

<h4 class="text-center">Explore the top rated books
</h4>


<div class="row books text-center">
  {% for book in books %}
    
    <div class="col-xs-12 col-sm-3 col-md-2 form-group">
      <div class="cover-grid">
        <span class="helper"></span>
        <a class="black" href="{{ url_for('bookshelves.show_get', user_id=book.user.id, book_id=book.book.id) }}">
          <img src="{{ book.book.image_url }}">
        </a>
      </div>
      <div>
        {{ book.rating }} out of 10
      </div>
    </div>

  {% endfor %}

  <div class="row text-center">
    <div class="col-xs-10 col-xs-offset-1">
      <a href="{{ url_for('users.index') }}"><span class="glyphicon glyphicon glyphicon-arrow-left glyphicon-large"></span><span> Back to what your friends are reading</span></a>
    </div>
  </div>

</div>


{% endblock %}

project/users/templates/users/edit_password.html
{% extends 'base.html' %}
{% block content %}

{% for message in get_flashed_messages() %}
  <div class="alert alert-info">{{ message }}</div>
{% endfor %}


<div class="row login">
  <div class="col-xs-12 col-sm-6 col-sm-offset-4">

    <h3>Change password</h3>

    <form action="{{ url_for('users.edit_password', user_id=user.id) }}?_method=PATCH" method="POST">
      {{ form.csrf_token }}
      <p>
        {{ form.old_password(placeholder="old password") }}
        <span class="text-danger">
          {% if form.old_password.errors %}
            {% for error in form.old_password.errors %}
              {{ error }}
            {% endfor %}
          {% endif %}
        </span>
      </p>
      <p>
        {{ form.new_password(placeholder="new password") }}
        <span class="text-danger">
          {% if form.new_password.errors %}
            {% for error in form.new_password.errors %}
              {{ error }}
            {% endfor %}
          {% endif %}
        </span>
      </p>
      <p>
        {{ form.confirm_password(placeholder="confirm new password") }}
        <span class="text-danger">
          {% if form.confirm_password.errors %}
            {% for error in form.confirm_password.errors %}
              {{ error }}
            {% endfor %}
          {% endif %}
        </span>
      </p>
      <button type="submit" class="btn btn-secondary">Update password</button>
    </form>
  </div>
</div>

{% endblock %}

project/users/templates/users/followers.html
{% extends 'base.html' %}
{% block content %}


{% for message in get_flashed_messages() %}
  <div class="alert alert-info">{{ message }}</div>
{% endfor %}



<h2 class="text-center">Followers
</h2>

<h4 class="text-center">Check out who is following {% if current_user.id == user.id %}you{% else %}{{ user.username }}{% endif %}
</h4>
<div class="col-xs-10 col-xs-offset-1 text-center">
    <a href="{{ url_for('users.following', user_id=user.id) }}">Following </span><span class="glyphicon glyphicon-arrow-right glyphicon-large"></span></a>
</div>


  <div class="row books text-center">

    {% for follower in user.all_followers %}
      <div class="col-xs-12 col-sm-3 col-md-2 form-group">
        <div>
          {# <span class="helper"></span> #}
          <a href="{{ url_for('users.show', user_id=follower.id) }}"><h5>{{ follower.username }}</h5>
          </a>
          {% if current_user.is_authenticated %}
            {% if current_user.is_following(follower) %}
              <form method="POST" action="{{url_for('users.follower', follower_id=follower.id)}}?_method=DELETE">
                <input type="submit" value="Unfollow" class="btn btn-warning">
              </form>
            {% else %}
              <form method="POST" action="{{url_for('users.follower', follower_id=follower.id)}}">
                <input type="submit" value="Follow" class="btn btn-info">
              </form>
            {% endif %}
          {% endif %}
        </div>
      </div>

    {% endfor %}

  </div> 


{% endblock %}

project/users/templates/users/following.html
{% extends 'base.html' %}
{% block content %}


{% for message in get_flashed_messages() %}
  <div class="alert alert-info">{{ message }}</div>
{% endfor %}

<h2 class="text-center">Following
</h2>

<h4 class="text-center">Check out who {% if current_user.id == user.id %}you are{% else %}{{ user.username }} is{% endif %} following 
</h4>

<div class="col-xs-10 col-xs-offset-1 text-center">
    <a href="{{ url_for('users.followers', user_id=user.id) }}"><span>Followers </span><span class="glyphicon glyphicon-arrow-right glyphicon-large"></span></a>
</div>


  <div class="row books text-center">

    {% for following in user.all_following %}
      <div class="col-xs-12 col-sm-3 col-md-2 form-group">
        <div>
          {# <span class="helper"></span> #}
          <a href="{{ url_for('users.show', user_id=following.id) }}"><h5>{{ following.username }}</h5>
          </a>
          {% if current_user.is_authenticated %}
            {% if current_user.is_following(following) %}
              <form method="POST" action="{{url_for('users.follower', follower_id=following.id)}}?_method=DELETE">
                <input type="submit" value="Unfollow" class="btn btn-warning">
              </form>
            {% else %}
              <form method="POST" action="{{url_for('users.follower', follower_id=following.id)}}">
                <input type="submit" value="Follow" class="btn btn-info">
              </form>
            {% endif %}
          {% endif %}
        </div>
      </div>
    {% endfor %}

  </div> 



{% endblock %}

project/users/templates/users/index.html
{% extends 'base.html' %}
{% block content %}

{% for message in get_flashed_messages() %}
  <div class="alert alert-info">{{ message }}</div>
{% endfor %}


<h2 class="text-center">Need inspiration?
</h2>

<h4 class="text-center">Check out what your friends are reading
</h4>


<div class="row books text-center">
  {% for book in books %}
    
    <div class="col-xs-12 col-sm-3 col-md-2 form-group">
      <div class="cover-grid">
        <span class="helper"></span>
        <a class="black" href="{{ url_for('bookshelves.show_get', user_id=book.user.id, book_id=book.book.id) }}">
          <img src="{{ book.book.image_url }}">
        </a>
      </div>
      <div>
        {{ book.rating }} out of 10
      </div>
    </div>

  {% endfor %}
</div>


{% endblock %}

project/users/templates/users/login.html
{% extends 'base.html' %}
{% block content %}


{% for message in get_flashed_messages() %}
  <div class="alert alert-info">{{ message }}</div>
{% endfor %}

<div class="row login">
  <div class="col-xs-12 col-sm-6 col-sm-offset-4">



    <h3>Please login</h3>

    <form action="{{ url_for('users.login') }}" method="POST">
      {{ form.csrf_token }}
      <p>
        {{ form.username(placeholder="username", autofocus="autofocus") }}
        <span class="text-danger">
          {% if form.username.errors %}
            {% for error in form.username.errors %}
              {{ error }}
            {% endfor %}
          {% endif %}
        </span>
      </p>
      <p>
        {{ form.password(placeholder="password") }}
        <span class="text-danger">
          {% if form.password.errors %}
            {% for error in form.password.errors %}
              {{ error }}
            {% endfor %}
          {% endif %}
        </span>
      </p>

      <button type="submit" class="btn btn-secondary">Log in</button>
    </form>
  </div>
</div>

{% endblock %}

project/users/templates/users/show.html
{% extends 'd3.html' %}
{% block content %}

{% for message in get_flashed_messages() %}
  <div class="alert alert-info">{{ message }}</div>
{% endfor %}

<h3 class="text-center">{{ user.username }}</h3>

<p class="text-center">
  <strong>{{ user.name }}</strong>
</p>

<div class="text-center">
    <span>
      <a href="{{ url_for('users.followers', user_id=user.id) }}"><span>Followers</span></a>
    </span>
    <span> | </span>
    <span>
      <a href="{{ url_for('users.following', user_id=user.id) }}"><span>Following</span></a>
    </span>
</div>



<div class="container">
  <div class="row text-center">
    <div class="col-xs-12 col-sm-6">
      <div class="shelf-photo-holder">
        <a href="{{ url_for('booklists.index', user_id=user.id) }}">
          <div class="black-rounded">
            <img src="{{ url_for('static', filename='images/booklist.jpg') }}">
          </div>
          <div>
            <h2><strong> Booklist</strong></h2>
          </div>
        </a>
            <h6>
              (Books you want to read)
            </h6>
      </div>

      
      <div class="bottom-margin">
        <small>({{ booklist|length }} book{% if booklist|length != 1 %}s{% endif %})</small>
      </div>
    </div>
      

    <div class="col-xs-12 col-sm-6">

      <div class="shelf-photo-holder">
        <a href="{{ url_for('bookshelves.index', user_id=user.id) }}">
          <div class="black-rounded">
            <img src="{{ url_for('static', filename='images/bookshelf.jpg') }}">
          </div>
          <div>
            <h2><strong> Bookshelf</strong></h2>
          </div>
        </a>
            <h6>
              (Books you've finished)
            </h6>
      </div>
      <div class="bottom-margin">
        <small>({{ bookshelf|length }} book{% if bookshelf|length != 1 %}s{% endif %})</small>
      </div>
        
    </div>
  </div>
</div>

<div class="center row">
  <h6>{% if average_rating != "None" %}<h5>Vizualize {% if current_user.id == user.id %}your{% else %}{{ user.username }}'s{% endif %} book reviews</h5>{% endif %}
  
  <h6>{% if average_rating != "None" %}Average rating: {{ average_rating }}{% else %}No reviews yet{% endif %}</h6>
  {% if average_rating != "None" %}
    <svg></svg>
  {% endif %}
</div>

<div class="text-center">

  {# <h5>More options</h5> #}

  {% if current_user.id == user.id %}
    <div>
      <a href="{{ url_for('users.edit', user_id=user.id) }}">Edit account settings</a>
    </div>

    <div>
      <a href="{{ url_for('users.edit_password', user_id=user.id) }}">Change password</a>
    </div>


  {% elif current_user.is_authenticated %}
    {% if current_user.is_following(user) %}
      <form method="POST" action="{{url_for('users.follower', follower_id=user.id)}}?_method=DELETE">
        <input type="submit" value="Unfollow" class="btn btn-warning">
      </form>
    {% else %}
      <form method="POST" action="{{url_for('users.follower', follower_id=user.id)}}">
        <input type="submit" value="Follow" class="btn btn-info">
      </form>
    {% endif %}
  {% endif %}
</div>






{% endblock %}

project/users/templates/users/signup.html
{% extends 'base.html' %}
{% block content %}


{% for message in get_flashed_messages() %}
  <div class="alert alert-info">{{ message }}</div>
{% endfor %}


<div class="row login">
  <div class="col-xs-12 col-sm-6 col-sm-offset-4">

    <h3>Sign up for an account</h3>
    <form action="{{ url_for('users.signup') }}" method="POST">
      {{ form.csrf_token }}
      <p>
        {{ form.username(placeholder="username", autofocus="autofocus") }}
        <span class="text-danger">
          {% if form.username.errors %}
            {% for error in form.username.errors %}
              {{ error }}
            {% endfor %}
          {% endif %}
        </span>
      </p>
      <p>
        {{ form.password(placeholder="password") }}
        <span class="text-danger">
          {% if form.password.errors %}
            {% for error in form.password.errors %}
              {{ error }}
            {% endfor %}
          {% endif %}
        </span>
      </p>
      <p>
        {{ form.email(placeholder="email") }}
        <span class="text-danger">
          {% if form.email.errors %}
            {% for error in form.email.errors %}
              {{ error }}
            {% endfor %}
          {% endif %}
        </span>
      </p>
      <p>
        {{ form.name(placeholder="name") }}
        <span class="text-danger">
          {% if form.name.errors %}
            {% for error in form.name.errors %}
              {{ error }}
            {% endfor %}
          {% endif %}
        </span>
      </p>

      <button type="submit" class="btn btn-secondary">Sign up</button>
    </form>
  </div>
</div>


{% endblock %}