project/bookshelves/models.py
# None needed -- uses the Book model from booklists folder

project/bookshelves/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, HiddenField, RadioField
from wtforms.validators import DataRequired, NumberRange, AnyOf, Email
from wtforms.widgets import TextArea


class BookshelfForm(FlaskForm):
    title = HiddenField()#StringField('title', validators=[DataRequired()])
    author = HiddenField()#StringField('author', validators=[DataRequired()])
    categories=HiddenField()#StringField('categories') 
    snippet=HiddenField()#StringField('snippet') 
    description=HiddenField()#StringField('description')  
    pages=HiddenField()#StringField('pages')  
    image_url=HiddenField()#StringField('image_url')  
    preview_url=HiddenField()#StringField('preview_url')  
    date_published=HiddenField()#StringField('date_published') 
    nyt_review_url=HiddenField() 
    rating = RadioField('rating', choices=[("1",1),("2",2),("3",3),("4",4),("5",5),("6",6),("7",7),("8",8),("9",9),("10",10)], default='1', validators=[DataRequired()])
    review = StringField('review', widget=TextArea())

class EditBookshelfForm(FlaskForm):
    rating = RadioField('rating', choices=[("1",1),("2",2),("3",3),("4",4),("5",5),("6",6),("7",7),("8",8),("9",9),("10",10)], default='1', validators=[DataRequired()])
    review = StringField('review', widget=TextArea())

class EmailForm(FlaskForm):
    recipient = StringField('email', validators=[DataRequired(), Email()])

project/booklists/views.py
from flask import redirect, render_template, request, url_for, Blueprint, flash
from project.booklists.models import Book
from project.users.models import User, Booklist
from project.booklists.forms import BooklistForm, EditBooklistForm
from project.bookshelves.forms import EditBookshelfForm
from project import db, bcrypt
from sqlalchemy.exc import IntegrityError
from flask_login import current_user, login_required
from functools import wraps

booklists_blueprint = Blueprint(
  'booklists',
  __name__,
  template_folder='templates'
)

def ensure_correct_user(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        if kwargs.get('user_id') != current_user.id:
            flash("Not authorized")
            return redirect(url_for('users.index'))
        return fn(*args, **kwargs)
    return wrapper

@booklists_blueprint.route('/', methods=["GET","POST"])
@login_required
def index(user_id):
  user = User.query.get_or_404(user_id)
  form = BooklistForm(request.form)
  if request.method == "POST":
    if form.validate():
      new_book = Book(
        title=request.form['title'],
        author=request.form['author'],
        categories=request.form['categories'],
        snippet=request.form['snippet'],
        description=request.form['description'],
        pages=request.form['pages'],
        image_url=request.form['image_url'],
        preview_url=request.form['preview_url'],
        date_published=request.form['date_published'],
        nyt_review_url=request.form['nyt_review_url'] 
      )
      # check if this book is already in the database - if it is, don't add it
      found_book = Book.query.filter_by(title=new_book.title).filter_by(author=new_book.author)
      if found_book.count() > 0:
        book_to_add=found_book.first()
      else:
        # only if not in the database already
        db.session.add(new_book)
        db.session.commit()
        book_to_add=new_book
      new_booklist = Booklist(
        list_type='booklist',
        comments=request.form['comments'],
        rating=1,
        review='',
        user=user,
        book=book_to_add
      )
      db.session.add(new_booklist)
      db.session.commit()
      flash("Book added successfully!")
      return redirect(url_for('booklists.index', user_id=user_id))
    flash("Please try again")
    return render_template('booklists/new.html', form=form, user=user)
  all_books = Booklist.query.filter_by(user=user).filter_by(list_type="booklist").all()
  # Look into N+1 query issue
  return render_template('booklists/index.html', form=form, user=user, books=all_books)


@booklists_blueprint.route('/new')
@login_required
@ensure_correct_user
def new(user_id):
  form = BooklistForm(request.form)
  user = User.query.get_or_404(user_id)
  return render_template('booklists/new.html', form=form, user=user)

@booklists_blueprint.route('/<int:book_id>', methods=["POST","PATCH","DELETE"])
@login_required
@ensure_correct_user
def show(user_id, book_id):
  book = Book.query.get_or_404(book_id)
  user = User.query.get_or_404(user_id)
  if request.method== "POST":
    form = EditBooklistForm(request.form)
    if form.validate():
      new_booklist = Booklist(
        list_type='booklist',
        comments=request.form['comments'],
        rating=1,
        review='',
        user=user,
        book=book
      )
      db.session.add(new_booklist)
      db.session.commit()
      flash("Book added successfully!")
      return redirect(url_for('booklists.index', user_id=user_id))
    flash("Please try again")
    return render_template('booklists/new.html', form=form, user=user)

  booklist = Booklist.query.filter_by(user=user).filter_by(book=book).first()
  if request.method == b"PATCH":
    form = EditBooklistForm(request.form)
    if form.validate():
      # make it so they can only update the comments OR move to their bookshelf!!!!!
      booklist.comments = request.form['comments']
      db.session.add(booklist)
      db.session.commit()
      flash("Book successfully updated")
      return redirect(url_for('booklists.index', user_id=user_id))
  if request.method == b"DELETE":
    form = EditBooklistForm(request.form)
    if form.validate():
      db.session.delete(booklist)
      # db.session.delete(book)
      db.session.commit()
      flash("Book successfully removed from your booklist")
      return redirect(url_for('booklists.index', user_id=user_id))

@booklists_blueprint.route('/<int:book_id>', methods=["GET"])
@login_required
# @ensure_correct_user
def show_get(user_id, book_id):
  book = Book.query.get_or_404(book_id)
  user = User.query.get_or_404(user_id)
  booklist = Booklist.query.filter_by(user=user).filter_by(book=book).first()
  full_bookshelf = Booklist.query.filter_by(book=book).filter_by(list_type="bookshelf").all()
  if len([b.rating for b in full_bookshelf]) == 0:
    average_rating = "No ratings yet"
  else:
    average_rating = round(sum([b.rating for b in full_bookshelf])/len([b.rating for b in full_bookshelf])/1)
  if booklist.user.id !=  current_user.id:
    form = EditBooklistForm(request.form)
  else:
    form = EditBookshelfForm(request.form)
  return render_template('booklists/show.html', book=booklist, form=form, user=user, full_bookshelf=full_bookshelf, average_rating=average_rating)

@booklists_blueprint.route('/<int:book_id>/edit')
@login_required
@ensure_correct_user
def edit(user_id, book_id):
  # Need to think about how to let them move a book to their bookshelf!!!!!!
  book = Book.query.get_or_404(book_id)
  user = User.query.get_or_404(user_id)
  form = EditBooklistForm(request.form)
  return render_template('booklists/edit.html', book=book, form=form, user=user)

project/bookshelves/views.py
from flask import redirect, render_template, request, url_for, Blueprint, flash
from flask_mail import Message
from project.booklists.models import Book
from project.users.models import User, Booklist
from project.bookshelves.forms import BookshelfForm, EditBookshelfForm, EmailForm
from project.booklists.forms import EditBooklistForm
from project import db, bcrypt, mail
from sqlalchemy.exc import IntegrityError
from sqlalchemy.sql import func
from flask_login import current_user, login_required
from functools import wraps

bookshelves_blueprint = Blueprint(
  'bookshelves',
  __name__,
  template_folder='templates'
)

def ensure_correct_user(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        if kwargs.get('user_id') != current_user.id:
            flash("Not authorized")
            return redirect(url_for('users.index'))
        return fn(*args, **kwargs)
    return wrapper

@bookshelves_blueprint.route('/', methods=["GET","POST"])
@login_required
def index(user_id):
  user = User.query.get_or_404(user_id)
  form = BookshelfForm(request.form)
  if request.method == "POST":
    if form.validate():
      new_book = Book(
        title=request.form['title'],
        author=request.form['author'],
        categories=request.form['categories'],
        snippet=request.form['snippet'],
        description=request.form['description'],
        pages=request.form['pages'],
        image_url=request.form['image_url'],
        preview_url=request.form['preview_url'],
        date_published=request.form['date_published'],
        nyt_review_url=request.form['nyt_review_url']
      )
      # check if this book is already in the database - if it is, don't add it
      found_book = Book.query.filter_by(title=new_book.title).filter_by(author=new_book.author)
      if found_book.count() > 0:
        book_to_add=found_book.first()
      else:
        # only if not in the database already
        db.session.add(new_book)
        db.session.commit()
        book_to_add=new_book
      new_bookshelf = Booklist(
        list_type='bookshelf',
        comments='',
        rating=request.form['rating'],
        review=request.form['review'],
        user=user,
        book=book_to_add
      )
      db.session.add(new_bookshelf)
      db.session.commit()
      flash("Book added successfully!")
      return redirect(url_for('bookshelves.index', user_id=user_id))
    flash("Please try again")
    return render_template('bookshelves/new.html', form=form, user=user)
  all_books = Booklist.query.filter_by(user=user).filter_by(list_type="bookshelf").all()
  # Look into N+1 query issue
  return render_template('bookshelves/index.html', form=form, user=user, books=all_books)


@bookshelves_blueprint.route('/new')
@login_required
@ensure_correct_user
def new(user_id):
  form = BookshelfForm(request.form)
  user = User.query.get_or_404(user_id)
  return render_template('bookshelves/new.html', form=form, user=user)

@bookshelves_blueprint.route('/<int:book_id>', methods=["PATCH","DELETE"])
@login_required
@ensure_correct_user
def show(user_id, book_id):
  book = Book.query.get_or_404(book_id)
  user = User.query.get_or_404(user_id)
  bookshelf = Booklist.query.filter_by(user=user).filter_by(book=book).first()
  form = EditBookshelfForm(request.form)
  if request.method == b"PATCH":
    if form.validate():
      bookshelf.rating = request.form['rating']
      bookshelf.review = request.form['review']
      bookshelf.list_type = "bookshelf"
      db.session.add(bookshelf)
      db.session.commit()
      flash("Book successfully updated")
      return redirect(url_for('bookshelves.index', user_id=user_id))
  if request.method == b"DELETE":
    if form.validate():
      db.session.delete(bookshelf)
      # db.session.delete(book)
      db.session.commit()
      flash("Book successfully removed from your bookshelf")
      return redirect(url_for('bookshelves.index', user_id=user_id))

@bookshelves_blueprint.route('/<int:book_id>', methods=["GET"])
@login_required
# @ensure_correct_user
def show_get(user_id, book_id):
  book = Book.query.get_or_404(book_id)
  user = User.query.get_or_404(user_id)
  bookshelf = Booklist.query.filter_by(user=user).filter_by(book=book).first()
  full_bookshelf = Booklist.query.filter_by(book=book).filter_by(list_type="bookshelf").all()
  if len([b.rating for b in full_bookshelf]) == 0:
    average_rating = "No ratings yet"
  else:
    average_rating = round(sum([b.rating for b in full_bookshelf])/len([b.rating for b in full_bookshelf]),1)
  if bookshelf.user.id !=  current_user.id:
    form = EditBooklistForm(request.form)
  else:
    form = EmailForm(request.form)
  return render_template('bookshelves/show.html', book=bookshelf, form=form, user=user, full_bookshelf=full_bookshelf, average_rating=average_rating)

@bookshelves_blueprint.route('/<int:book_id>/edit')
@login_required
@ensure_correct_user
def edit(user_id, book_id):
  # Need to think about how to let them move a book to their bookshelf!!!!!!
  book = Book.query.get_or_404(book_id)
  user = User.query.get_or_404(user_id)
  form = EditBookshelfForm(request.form)
  return render_template('bookshelves/edit.html', book=book, form=form, user=user)

@bookshelves_blueprint.route('/<int:book_id>/email',methods=["POST"])
@login_required
@ensure_correct_user
def email(user_id, book_id):
  form = EmailForm(request.form)
  book = Book.query.get_or_404(book_id)
  user = User.query.get_or_404(user_id)
  bookshelf = Booklist.query.filter_by(user=user).filter_by(book=book).first()
  recipients = request.form['recipient'].split(',')

  if form.validate_on_submit():
    msg = Message("Here's a book I thought you might like",
                sender=(current_user.name,current_user.email),
                recipients=recipients)
    msg.body = render_template('bookshelves/email.html', user=user, book=bookshelf)
    msg.html = render_template('bookshelves/email.html', user=user, book=bookshelf)
    mail.send(msg)
    return redirect(url_for('bookshelves.index', user_id=user.id))
  flash("Invalid email address. Please try again.")
  return render_template('bookshelves/show.html', form=form, book=bookshelf, user=user)

project/bookshelves/templates/bookshelves/edit.html
{% extends 'base.html' %}
{% block content %}

{% for message in get_flashed_messages() %}
  <div class="alert alert-info">{{ message }}</div>
{% endfor %}



<div class="row text-center login">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1">
    <h3>Edit review of <strong>{{ book.title }}</strong></h3>
    <section>
      <div class="row">
        <div class="text-center">
          <form action="{{ url_for('bookshelves.show', user_id=user.id, book_id=book.id) }}?_method=PATCH" method="POST">
            <div class="form-group">
              <div class="col-xs-10 col-xs-offset-1 text-center add-form">
            
                {{ form.csrf_token }}

                 <p class="rating">rating
                  {% for subfield in form.rating %}
                      <tr>
                          <td>{{ subfield(class="radio-inline") }}</td>
                          <td>{{ subfield.label }}</td>
                      </tr>
                  {% endfor %}
                  <span class="text-danger">
                    {% if form.rating.errors %}
                      {% for error in form.rating.errors %}
                        {{ error }}
                      {% endfor %}
                    {% endif %}
                  </span>
                </p>
                <p>
                  {{ form.review(placeholder="review", class="form-control") }}
                  <span class="text-danger">
                    {% if form.review.errors %}
                      {% for error in form.review.errors %}
                        {{ error }}
                      {% endfor %}
                    {% endif %}
                  </span>
                </p>
              </div>
              <div class="col-xs-12">
                <button type="submit align-right" class="btn btn-default search">Save changes</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </section>

<form action="{{ url_for('bookshelves.show', user_id=user.id, book_id=book.id) }}?_method=DELETE" method="POST">
  {{ form.csrf_token }}
  <button type="submit" class="btn btn-danger">Delete book</button>
</form>
<br>
<br>


<div class="row text-center">
  <div class="col-xs-10 col-xs-offset-1">
    <a href="{{ url_for('bookshelves.show_get', user_id=user.id, book_id=book.id) }}"><span class="glyphicon glyphicon-arrow-left glyphicon-large"></span><span> Back to {{ book.title }}</span></a>
  </div>
</div>

{% endblock %}

project/bookshelves/templates/bookshelves/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Recommendation</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">

    <style>
  
      h1, h2, h3, h4, h5, h6 {
        font-family: 'Abril Fatface';
      }

      .blockquote-reverse {
        margin-top: 2rem;
        background-color: #B4D6DE;
      }

      .blockquote-reverse footer {
        color: gray;
      }

    </style>

</head>
<body>

      Hello,

      I thought you might like this book.


    <h3>{{ book.book.title }}</h3>
    <img src="{{ book.book.image_url }}">
    <blockquote class="blockquote-reverse">
      <p>
        {{ book.review }}
      </p>
      <p>
        {{ user.username }}'s review ({{ book.rating }} out of 10)
      </p>
    </blockquote>
      
    <h3>About this book</h3>
    <div>
      <strong>Author</strong>: {{ book.book.author }}
    </div>
    <div>
      <strong>Pages</strong>: {{ book.book.pages }}
    </div>
    <div>
      <strong>Date Published</strong>: {{ book.book.date_published }}
    </div>
    <div>
      <strong>About</strong>: {{ book.book.description }}
    </div>
    <div>
      <strong>Category</strong>: {{ book.book.categories }}
    <div>
      {% if book.book.nyt_review_url != "None found" and book.book.nyt_review_url != None %}<strong>Published Review</strong>: <a href="{{ book.book.nyt_review_url }}">New York Times book review</a>{% endif %}
    </div>
     
  </section>


  <br>
  <br>


    <p>
      Brought to you by <a href="https://my-bookshelves.herokuapp.com">My Bookshelves</a>.
    </p>
    <div>
      <img src="http://imgur.com/I72VCwf.jpg">
    </div>
  </footer>


    

  </div>
    
</body>
</html>

project/bookshelves/templates/bookshelves/index.html
{% extends 'base.html' %}
{% block content %}

{% for message in get_flashed_messages() %}
  <div class="alert alert-info">{{ message }}</div>
{% endfor %}

<h2 class="text-center">{{ user.username }}'s Bookshelf
</h2>
  <div class="col-xs-10 col-xs-offset-1 text-center">
    <a href="{{ url_for('booklists.index', user_id=user.id) }}"><span>Switch to {% if current_user.id == user.id %}my{% else %}{{ user.username }}'s{% endif %} booklist </span><span class="glyphicon glyphicon-arrow-right glyphicon-large"></span></a>
  </div>

  <div class="row books text-center">
    {% for book in books %}
      
      <div class="col-xs-12 col-sm-3 col-md-2 form-group">
        <div class="cover-grid">
          <span class="helper"></span>
          <a class="black" href="{{ url_for('bookshelves.show_get', user_id=user.id, book_id=book.book.id) }}">
            <img src="{{ book.book.image_url }}">
          </a>
        </div>
        <div>
          {{ book.rating }} out of 10
        </div>
      </div>

    {% endfor %}

    <div class="col-xs-10 col-xs-offset-1 text-center">
    <a href="{{ url_for('users.show', user_id=user.id) }}"><span class="glyphicon glyphicon-arrow-left glyphicon-large"></span><span> Back to {% if current_user.id == user.id %}my{% else %}{{ user.username }}'s{% endif %} profile page</span></a>
  </div>
  </div>
{# </div> #}
{% endblock %}

project/bookshelves/templates/bookshelves/new.html
{% extends 'base.html' %}
{% block content %}

{% for message in get_flashed_messages() %}
  <div class="alert alert-info">{{ message }}</div>
{% endfor %}

  <div class="container">
    <section class="top container">
      <h2 class="header text-center">Search for a Book
      </h2>
      <h4 class="header text-center">To add to your bookshelf
      </h4>
    </section>
    <section class="top container">
      <div class="row">
        <form class="form" action="javascript:void(0)">
          <div class="form-group">
            <div class="col-xs-12 col-sm-6 col-sm-offset-3">
              <label class="sr-only" for="title">Title (required)</label>
              <input type="text" class="form-control" id="searchTitle" placeholder="Title (required)" autofocus="autofocus">
              <label class="sr-only" for="author">Author (optional)</label>
              <input type="text" class="form-control" id="searchAuthor" placeholder="Author (optional)">
            </div>
          </div>
          <div class="col-xs-12 text-center">
            <button type="submit" class="btn btn-default search">Search
            </button>
          </div>
        </form>
      </div>
    </section>
    <section class="container">
      <div class="row">
        <div class="col-xs-12 text-center click">
          <h4>Click on a book to select it</h4>
        </div>
      </div>
    <hr class="click">
    </section>
    <section class="container">
      <div class="row bookshelf">
        <div class="col-xs-10 col-xs-offset-1 holder">
          <div class="col-xs-2 cover"></div>
          <div class="col-xs-10 list"></div>
        </div>
      </div>
    </section>
    <section>
      <div class="row">
        <div class="form-hidden text-center">
          <form class="form" action="{{ url_for('bookshelves.index', user_id=user.id) }}" method="POST">
            <div class="form-group">
              <div class="col-xs-10 col-xs-offset-1 text-center add-form">
            
                {{ form.csrf_token }}
                {{ form.title(placeholder="title") }}
                {{ form.author(placeholder="author") }}
                {{ form.categories(placeholder="categories") }}
                {{ form.snippet(placeholder="snippet") }}
                {{ form.description(placeholder="description") }}
                {{ form.pages(placeholder="pages") }}
                {{ form.image_url(placeholder="image url") }}
                {{ form.preview_url(placeholder="preview url") }}
                {{ form.date_published(placeholder="date published") }}
                {{ form.nyt_review_url(placeholder="NYT review url") }}

                <p class="rating">rating
                  {% for subfield in form.rating %}
                      <tr>
                          <td>{{ subfield(class="radio-inline") }}</td>
                          <td>{{ subfield.label }}</td>
                      </tr>
                  {% endfor %}
                  {# {{ form.rating(class="form-control") }} #}
                  <span class="text-danger">
                    {% if form.rating.errors %}
                      {% for error in form.rating.errors %}
                        {{ error }}
                      {% endfor %}
                    {% endif %}
                  </span>
                </p>
                <p>
                  {{ form.review(placeholder="review", class="form-control") }}
                  <span class="text-danger">
                    {% if form.review.errors %}
                      {% for error in form.review.errors %}
                        {{ error }}
                      {% endfor %}
                    {% endif %}
                  </span>
                </p>
              </div>
              <div class="col-xs-12">
                <button type="submit align-right" class="btn btn-default search">Add to bookshelf</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </section>

{% endblock %}

project/bookshelves/templates/bookshelves/show.html
{% extends 'base.html' %}
{% block content %}

{% for message in get_flashed_messages() %}
  <div class="alert alert-info">{{ message }}</div>
{% endfor %}



<div class="row">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1 text-center">
    {% if book.list_type == "bookshelf" %}
      <h3>{{ book.book.title }}</h3>
      <img src="{{ book.book.image_url }}">
      <blockquote class="blockquote-reverse">
        <p>
          {{ book.review }}
        </p>
        <footer>
          {{ user.username }}'s review ({{ book.rating }} out of 10)
        </footer>
      </blockquote>
      {% if current_user.id == user.id %}
        <a href="{{ url_for('bookshelves.edit', user_id=user.id, book_id=book.book.id) }}"><span class="glyphicon glyphicon-edit glyphicon-large"></span><span> Edit review</span></a>
      {% endif %}
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <h4>About this book</h4>
    <div>
      <strong>Author</strong>: {{ book.book.author }}
    </div>
    <div>
      <strong>Pages</strong>: {{ book.book.pages }}
    </div>
    <div>
      <strong>Date Published</strong>: {{ book.book.date_published }}
    </div>
    <div>
      <strong>About</strong>: {{ book.book.description }}
    </div>
    <div>
      <strong>Category</strong>: {{ book.book.categories }}
    </div>
    <div>
      {% if book.book.nyt_review_url != "None found" and book.book.nyt_review_url != None %}
      <span>
        <a target="_blank" href="http://developer.nytimes.com"><img src="{{ url_for('static', filename='images/nyt.png') }}"></a>
      </span>
      <strong>Published Review</strong>: <a target="_blank" href="{{ book.book.nyt_review_url }}">New York Times book review</a>
    {% endif %}
    </div>
  </div>
</div>
{% endif %}



{% if book.user.id !=  current_user.id %}

<div class="row text-center">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">

  <h5>
    <button type="button" class="btn btn-info" aria-label="Left Align">
      <span class="glyphicon glyphicon-plus glyphicon-large" aria-hidden="true"></span>
    </button>
    <span>Add to your booklist</span>
  </h5>
 </div>
</div>

    <section>
      <div class="row row-hidden">
        <div class="text-center">
          <form class="form" action="{{ url_for('booklists.show', user_id=current_user.id, book_id=book.book.id) }}" method="POST">
            <div class="form-group">
              <div class="col-xs-10 col-xs-offset-1 text-center add-form">
            
                {{ form.csrf_token }}

                <p>
                  {{ form.comments(placeholder="comments", class="form-control") }}
                  <span class="text-danger">
                    {% if form.comments.errors %}
                      {% for error in form.comments.errors %}
                        {{ error }}
                      {% endfor %}
                    {% endif %}
                  </span>
                </p>
              </div>
              <div class="col-xs-12">
                <button type="submit align-right" class="btn btn-default search">Add to booklist</button>
              </div>
            </div>
          </form>
        </div>
      </div>








{% else %}

<div class="row text-center">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">

  <h5>
    <button type="button" class="btn btn-info" aria-label="Left Align">
      <span class="glyphicon glyphicon-share-alt glyphicon-large" aria-hidden="true"></span>
    </button>
    <span>Email recommendation</span>
  </h5>
 </div>
</div>

    <section>
      <div class="row row-hidden">
        <div class="text-center">
          <form class="form" action="{{ url_for('bookshelves.email', user_id=user.id, book_id=book.book.id) }}" method="POST">
            <div class="form-group">
              <div class="col-xs-10 col-xs-offset-1 text-center add-form">
                {{ form.csrf_token }}                 
                <p>
                  {{ form.recipient(placeholder="recipient(s)", class="form-control active") }}
                  <span class="text-danger">
                    {% if form.recipient.errors %}
                      {% for error in form.recipient.errors %}
                        {{ error }}
                      {% endfor %}
                    {% endif %}
                  </span>
                </p>
              </div>
              <div class="col-xs-12">
                <button type="submit align-right" class="btn btn-default search">Send email</button>
              </div>
            </div>
          </form>
        </div>
      </div>

{% endif %}



<div class="row text-center">
  <div class="col-xs-10 col-xs-offset-1">
    <a href="{{ url_for('bookshelves.index', user_id=user.id) }}"><span class="glyphicon glyphicon-arrow-left glyphicon-large"></span><span> Back to {{ user.username }}'s bookshelf</span></a>
  </div>
</div>

</section>

{% if full_bookshelf|length > 1 %}

  <hr>
  <section>
    <div class="row text-center">
      <div class="col-xs-10 col-xs-offset-1">
        <h5>
          What others are saying
        </h5>
        <h6 class="bottom-margin-small">Average rating: {{ average_rating }}</h6>

        {% for reviews in full_bookshelf %}
          {% if reviews.book_id == book.book.id  and reviews.user_id != user.id %}
          
            <div class="col-xs-12 col-sm-3 col-md-2 form-group">
              <div>
                <strong>{{ reviews.rating }} out of 10</strong>
              </div>
              <div>
                {{ reviews.review }}
              </div>
              <div>
                - {{ reviews.user.username }}
              </div>
            </div>
          {% endif %}

        {% endfor %}

      </div>
    </div>
  </section>
{% endif %}

{% endblock %}